import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * M4 — seeds game content from `bunker_cards_ua_v7.xlsx`. Idempotent within
 * one run; will fail if executed twice without first emptying the tables
 * (re-applying this migration is not the intended way to refresh content —
 * write a new migration that UPSERTs by stable text).
 *
 * Counts at seed time:
 *   traits        576
 *   apocalypses   30
 *   shelters      30
 *   biology_age   71
 *   biology_weight 75
 *   biology_sex    2
 *   biology_gender 24
 *   biology_race   50
 */
export class GameSeed1779126000000 implements MigrationInterface {
  name = 'GameSeed1779126000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await this.seedTraits(queryRunner);
    await this.seedBiology(queryRunner, 'biology_age', BIOLOGY_AGE);
    await this.seedBiology(queryRunner, 'biology_weight', BIOLOGY_WEIGHT);
    await this.seedBiology(queryRunner, 'biology_sex', BIOLOGY_SEX);
    await this.seedBiology(queryRunner, 'biology_gender', BIOLOGY_GENDER);
    await this.seedBiology(queryRunner, 'biology_race', BIOLOGY_RACE);
    await this.seedShelters(queryRunner);
    await this.seedApocalypses(queryRunner);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "apocalypse"`);
    await queryRunner.query(`DELETE FROM "shelter"`);
    await queryRunner.query(`DELETE FROM "biology_race"`);
    await queryRunner.query(`DELETE FROM "biology_gender"`);
    await queryRunner.query(`DELETE FROM "biology_sex"`);
    await queryRunner.query(`DELETE FROM "biology_weight"`);
    await queryRunner.query(`DELETE FROM "biology_age"`);
    await queryRunner.query(`DELETE FROM "trait"`);
  }

  private async seedTraits(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO "trait" ("kind", "polarity", "titleUk")
       SELECT *
       FROM unnest($1::"public"."trait_kind_enum"[],
                   $2::"public"."polarity_enum"[],
                   $3::text[])`,
      [
        TRAITS.map((trait) => trait.kind),
        TRAITS.map((trait) => trait.polarity),
        TRAITS.map((trait) => trait.titleUk),
      ],
    );
  }

  private async seedBiology(
    queryRunner: QueryRunner,
    table: string,
    values: string[],
  ): Promise<void> {
    await queryRunner.query(
      `INSERT INTO "${table}" ("valueUk") SELECT * FROM unnest($1::text[])`,
      [values],
    );
  }

  private async seedShelters(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO "shelter"
        ("areaUk", "locationUk", "durationUk", "equipmentUk", "suppliesUk", "polarity")
       SELECT *
       FROM unnest($1::text[], $2::text[], $3::text[], $4::text[], $5::text[],
                   $6::"public"."polarity_enum"[])`,
      [
        SHELTERS.map((shelter) => shelter.areaUk),
        SHELTERS.map((shelter) => shelter.locationUk),
        SHELTERS.map((shelter) => shelter.durationUk),
        SHELTERS.map((shelter) => shelter.equipmentUk),
        SHELTERS.map((shelter) => shelter.suppliesUk),
        SHELTERS.map((shelter) => shelter.polarity),
      ],
    );
  }

  private async seedApocalypses(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO "apocalypse"
        ("nameUk", "descriptionUk", "populationRemainderUk", "polarity")
       SELECT *
       FROM unnest($1::text[], $2::text[], $3::text[],
                   $4::"public"."polarity_enum"[])`,
      [
        APOCALYPSES.map((row) => row.nameUk),
        APOCALYPSES.map((row) => row.descriptionUk),
        APOCALYPSES.map((row) => row.populationRemainderUk),
        APOCALYPSES.map((row) => row.polarity),
      ],
    );
  }
}

const TRAITS: { kind: string; polarity: string; titleUk: string }[] = [
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Лікар-хірург"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Військовий медик"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Медсестра реанімації"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Стоматолог-універсал"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Біолог-генетик"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Інженер-електрик"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Програміст із досвідом «залізо»"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Електрик-високовольтник"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Сантехнік-золоті руки"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Зварювальник 6-го розряду"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Тесля з 20-річним досвідом"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Агроном"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Фермер-універсал"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Пасічник"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Ветеринар"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Військовий снайпер"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Боєць ССО"},
      {"kind":"PROFESSION","polarity":"POSITIVE","titleUk":"Шеф-кухар польовий"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Архітектор"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Художник-графік"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Гітарист рок-гурту"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Журналіст"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Перекладач англ.-укр."},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Юрист"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Бухгалтер"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Менеджер з продажів"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"HR-спеціаліст"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Логіст"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Перукар чоловічий"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Масажист тайського стилю"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Фітнес-тренер"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Боксер-важковаговик"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Бариста (5-та хвиля кави)"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Кондитер-торти на замовлення"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Бортпровідник МАУ (екс)"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Таксист «Болт»"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Далекобійник Європа"},
      {"kind":"PROFESSION","polarity":"NEUTRAL","titleUk":"Капітан риболовецького судна"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Безробітний 5 років"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Тіктокер 1М підписників (танці)"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"OnlyFans-«модель»"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Ворожка з Інстаграму"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Астролог із журналу «Караван»"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Клоун-аніматор з похмурим минулим"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Колектор-вибивач"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Чиновник райдержадміністрації"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Депутат місцевої ради"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Рієлтор-обманщик"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Промоутер на вулиці"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Продавець БАДів"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"МЛМ-консультант (Гербалайф)"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Букмекер"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Тамада з 30-річним стажем"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Парапсихолог-цілитель"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Хіромант-провісник"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Езотерик-коуч"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Криптотрейдер на маржі x100"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Покерний професіонал-програш"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Танцюрист стриптизу"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Б’юті-блогерка (тушетіні)"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Розклейник оголошень про позики"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Спам-дзвонар від «Сбербанка»"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Шахрай-фішер з Тинди"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Дегустатор корму для котів"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Спеціаліст з вирощування цвілі"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"«Бітбоксер»-вуличник"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"«Коуч» з продажу повітря"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Скам-проповідник у Telegram"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Реселер кросівок Yeezy"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Дроп-шиппер з Aliexpress"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Тренер з «жіночої енергії»"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Тілесний інтегратор (масаж тіла «з історією»)"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Інста-філософ"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Стрімер по «Доті» 14 годин/добу"},
      {"kind":"PROFESSION","polarity":"NEGATIVE","titleUk":"Караоке-співак у переході"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Ідеальне здоров’я"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Залізний імунітет"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Орлиний зір"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Слух кажана"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Високий больовий поріг"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Група крові O- (універсальний донор)"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Жодних алергій"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Витривалість як у марафонця"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Швидке загоєння ран"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Підвищена стійкість до радіації"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Стійкість до холоду (моржує)"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Стійкість до спеки (пустеля рідна)"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Реакція як у Кіану Рівза"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Серце спортсмена"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Хороший нічний зір"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Стресостійкість бронетранспортера"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Здорова вагітність 10 тижнів"},
      {"kind":"HEALTH","polarity":"POSITIVE","titleUk":"Природна стійкість до отрут"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Короткозорість -1 (окуляри)"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Дальтонізм (плутає зелене/червоне)"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Шрам через все обличчя"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Усе тіло в татуюваннях"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Пірсинг у незвичних місцях"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Мігрень раз на місяць"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Сезонна алергія на пилок"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Непереносимість лактози"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Хропе як бензопила"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Сомнамбулізм (ходить уві сні)"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Хронічне безсоння"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Сколіоз"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Плоскостопість"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Сивина у 25"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Лисина як у Зеленського"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Вітиліго плямами"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Великий зріст 200 см"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Маленький зріст 150 см"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Завжди мерзне (як рептилія)"},
      {"kind":"HEALTH","polarity":"NEUTRAL","titleUk":"Веганська діета 10 років"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Астма (інгалятор кожні 3 год)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Епілепсія (часті напади)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Діабет 1 типу (інсулін-залежний)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Онкологія II стадії"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"ВІЛ"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Гепатит C"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Відкритий туберкульоз"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Цироз печінки"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Хвороба Паркінсона"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Хвороба Альцгеймера (рання)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Шизофренія параноїдна"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Біполярний розлад"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Глибока депресія"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Сліпота на обидва ока"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Повна глухота"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Німота"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Параліч нижніх кінцівок"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Ампутована рука"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Ампутована нога"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Гемофілія"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Анорексія"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Морбідне ожиріння 200 кг"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Анафілактичний шок на пил"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Аритмія смертельно небезпечна"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Постійний гемодіаліз"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Деменція (важка стадія)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Хронічна променева хвороба"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Термінальна стадія раку"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Хвороба Крона"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Розсіяний склероз"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Системний червоний вовчак"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Постійний понос (хвороба нез’ясованої етіології)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Алергія на сонячне світло"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Алергія на воду"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Алергія на власну сперму/секрет"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Алергія на роботу (психосоматика)"},
      {"kind":"HEALTH","polarity":"NEGATIVE","titleUk":"Гнилі зуби, постійний біль"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Полювання з нарізною зброєю"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Спортивна риболовля"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Виживання в дикій природі (4 рази на рік у тайзі)"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Туризм категорії 5"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Альпінізм (8000+ м)"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Стрільба з лука (КМС)"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Стрільба з пістолета IPSC"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Бойове самбо"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Городництво з гідропонікою"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Бджільництво"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Розведення курей і кролів"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Ремонт побутової електроніки"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Сварка-аргон"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Ковальство"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Гончарство"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Шиття і крій (одяг з нуля)"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Сироваріння"},
      {"kind":"HOBBY","polarity":"POSITIVE","titleUk":"Травознавство-фітотерапія"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Читання класики"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Шахи (1-й розряд)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Настільні ігри (Catan, Carcassonne)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Каліграфія"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Малювання акварель"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Йога (вранці 30 хв)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Медитація"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Ранкові пробіжки 10 км"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Велоспорт по вихідних"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Плавання басейн 3р/тиждень"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Гра на гітарі (3 акорди)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Гра на піаніно (любитель)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Аматорський театр"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Подкастинг про філософію"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Каякінг по Дністру"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Колекціонує марки УНР"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Кулінарія (борщ за 15 рецептами)"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Скетчинг у блокноті"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Орігамі"},
      {"kind":"HOBBY","polarity":"NEUTRAL","titleUk":"Бісероплетіння"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Шопоголізм («Епіцентр» — мій дім»)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Перегляд серіалів 24/7"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Залипання в TikTok 8 годин"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"«Доту» 12 годин/добу 5 років"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Азартні ігри (виграв одного разу — далі мовчання)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Ставки на спорт (мінус 50 тис.)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Косплей з саморобним мечем"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Караоке-вечірки кожні вихідні"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Аніме-марафони (100+ серій безперервно)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Збір мерчу «Атаки титанів»"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Утримання 30 котів у квартирі"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Розведення отруйних змій"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Розведення отруйних павуків"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Бейсджампінг"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Уличні нічні дрифт-гонки"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Руфінг (фоткається на дахах)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Сталкінг по покинутих заводах"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Чорна магія (свічки, кров кози)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Сатанинські ритуали по п’ятницях"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Спіритизм (запрошує бабусю в гості)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Ворожіння на картах Таро"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Езотеричні практики «реінкарнацій»"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Тренінги «вийди із зони комфорту»"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Фурі-рух (костюм лиса)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Збирання автографів зірок"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Дегустація дорогих вин (без розуміння)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Колекціонує нігті знаменитостей"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Збирає предмети з ІІ Світової (з символікою)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Доглядач смітників (думає що скарби)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Фанатично колекціонує квитки в кіно"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Збирає пляшки з-під «Закарпатського»"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Любить «вписати чарочку» зранку"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Філателіст із фанатизмом"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Грає в «Хрест-нолики» на гроші"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Розводить тарганів-бійців"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"«Кричить у порожнечу» (психопрактика)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Спить із плюшевим ведмедиком (40+ років)"},
      {"kind":"HOBBY","polarity":"NEGATIVE","titleUk":"Хобіхорсинг"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Мізофобія (страх бруду — все стерильно)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Бацилофобія (страх мікробів — гігієніст)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Радіофобія (страх радіації — обережний)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Пірофобія (страх вогню — пожежна безпека)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Токсикофобія (страх отруєнь)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Карцинофобія (страх раку — ЗОЖ)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Гефірофобія (страх мостів — у бункері неважливо)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Таласофобія (страх моря)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Авіафобія (страх літаків)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Айхмофобія (страх гострих — обережний)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Ксенофобія до нечистоти (помиє посуд завжди)"},
      {"kind":"PHOBIA","polarity":"POSITIVE","titleUk":"Гліттерофобія (страх блискіток — без сміття)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Арахнофобія (павуки)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Офідіофобія (змії)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Орнітофобія (птахи)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Акрофобія (висота)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Трискайдекафобія (число 13)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Тригонофобія (трикутники)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Кумпунофобія (ґудзики)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Трипофобія (отвори в купі)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Бронтофобія (гроза)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Хіонофобія (сніг)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Антофобія (квіти)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Турофобія (сир)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Лаханофобія (овочі)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Папафобія (Папа Римський)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Помпонофобія (помпони)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Меланофобія (чорний колір)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Гіппофобія (коні)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Гелотофобія (страх що з тебе сміються)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Хіонофобія (страх снігопаду)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Огрефобія (страх огрів — Шрек)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Кльоунофобія (страх клоунів)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Селенофобія (Місяць)"},
      {"kind":"PHOBIA","polarity":"NEUTRAL","titleUk":"Дендрофобія (дерева)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Клаустрофобія (замкнуті простори — пекельно в бункері)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Ніктофобія (темрява)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Гемофобія (кров)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Танатофобія (страх смерті — постійна паніка)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Некрофобія (трупи)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Демофобія (натовп)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Антропофобія (страх людей)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Соціофобія"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Аутофобія (страх самотності)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Монофобія (бути одному)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Ізолофобія (ізоляція)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Агорафобія (відкриті простори)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Атіхіфобія (страх невдач — паралізує)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Сомніфобія (страх сну)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Онейрофобія (страх снів)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Ергофобія (страх роботи)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Понофобія (страх втоми)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Децидофобія (приймати рішення)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Афенфосмофобія (дотики)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Еметофобія (блювання)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Аблутофобія (миття — смердюх)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Гідрофобія (вода — не п’є)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Аквафобія (вода взагалі)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Цибофобія (страх їжі)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Сітофобія (страх їсти)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Фагофобія (страх ковтати)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Спектрофобія (дзеркала)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Фармакофобія (страх ліків)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Трипанофобія (уколи — без щеплень)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Іатрофобія (страх лікарів)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Дентофобія (страх стоматологів)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Геронтофобія (страх літніх людей)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Педофобія (страх дітей)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Триаскадекафобія + клаустрофобія разом"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Барофобія (страх сили тяжіння)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Стазіфобія (страх стояти)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Кінесофобія (страх руху)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Хімофобія (страх будь-якої хімії — навіть мила)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Тилофобія (страх ватної палички)"},
      {"kind":"PHOBIA","polarity":"NEGATIVE","titleUk":"Філофобія (страх кохати — самотній псих)"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Природний лідер"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Рішучий, як таран"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Стресостійкий"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Емпатичний"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Працьовитий"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Дисциплінований"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Чесний до кістки"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Терплячий"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Винахідливий"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Холоднокровний"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Сміливий"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Командний гравець"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Мудрий не за віком"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Гнучке мислення"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Сила волі залізна"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Тактовний дипломат"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Самоконтроль монаха"},
      {"kind":"CHARACTER_TRAIT","polarity":"POSITIVE","titleUk":"Адаптивний"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Інтроверт"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Екстраверт"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Романтик"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Балакун"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Молчун"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Ревнивець"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Перфекціоніст"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Пунктуальний"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Соромливий"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Самоіронічний"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Серйозний як церковний дзвін"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Прагматик"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Ідеаліст"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Консерватор"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Атеїст-філософ"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Релігійний (нефанатично)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Мінімаліст"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Сова (засинає о 4)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Жайворонок (підйом о 5)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEUTRAL","titleUk":"Завжди голодний"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Агресивний (б’є з пів-оберту)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Запальний (від іскри — пожежа)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Лінивий до неможливого"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Егоїст 80-го рівня"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Жадібний (зимою снігу не випросиш)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Заздрить навіть собаці"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Бреше як дише"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Лицемір 95 рівня"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Підлий (нож у спину — стиль життя)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Боягуз — перший ховається"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Панікер (від чхання — паніка)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Істеричний (кричить 24/7)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Безвідповідальний"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Капризний як дитина"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Зверхній сноб"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Маніпулятор-токсик"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Мстивий — пам’ятає 30 років"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Нарцис — все про себе"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Соціопат"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Психопат"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Хронічний нюня"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Прокрастинатор — все на завтра"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Імпульсивний (думає опісля)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Алкоголік"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Наркоман"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Ігроман"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Гнівливий (червоніє, синіє, синяк)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Інтриган"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Расист"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Сексист"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Гомофоб"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Релігійний фундаменталіст"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Зрадливий («своїх» здає першим)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Завжди жертва (вічно «всі мені винні»)"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Любить пхати носа в чужі справи"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Без почуття гумору взагалі"},
      {"kind":"CHARACTER_TRAIT","polarity":"NEGATIVE","titleUk":"Завжди має «свою думку», але мовчить на голосуванні"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Повна аптечка з антибіотиками"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Інсулін і шприци"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Хірургічний набір"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Дозиметр"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Військовий протигаз"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Захисний костюм ОЗК"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Бензопила Stihl"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Каністра бензину 20 л"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Радіостанція з акумулятором"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Сонячна батарея 200 Вт"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Мультитул Leatherman"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Бензогенератор"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"50 кг насіння (пшениця, овочі)"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Фільтр LifeStraw"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Кресало + 200 сірників у воску"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Автомат + 1000 патронів"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Лук зі стрілами"},
      {"kind":"LUGGAGE","polarity":"POSITIVE","titleUk":"Енциклопедія медицини у 3 томах"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Гітара"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Колода гральних карт"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Шаховий набір"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Біблія"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Зошит і олівці"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Сімейний фотоальбом"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"50 рулонів туалетного паперу"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Господарське мило (10 шматків)"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Шампунь 3 пляшки"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Бритвенний набір"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Маленьке дзеркало"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Механічний годинник"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Календар на 10 років"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Блок сигарет"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Пляшка горілки «Хортиця» 1 л"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Електрочайник (працює лише з генератором)"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Чай 1 кг"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Кава в зернах 2 кг"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Шоколад «Світоч» 2 кг"},
      {"kind":"LUGGAGE","polarity":"NEUTRAL","titleUk":"Сухе молоко 5 кг"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Валіза брендового одягу"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Декоративна косметика"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Парфум Chanel №5"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Кришталева ваза прабабусі"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Картина Малевича (підробка)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Скрипка Страдіварі (не вміє грати)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"iPhone 16 Pro Max (без зв’язку)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"PS5 (без розетки)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Вінілові платівки Pink Floyd"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Рулетка казино"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"1 млн доларів готівкою (фантики)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Злиток золота 1 кг (важко тягати)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Каблучка з діамантом 2 карати"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Пляшка Dom Pérignon"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Банка чорної ікри 250 г"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Норкова шуба"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Туфлі Louboutin 41 розмір"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Сумка Hermès Birkin"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Кальян з тютюном"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Запас марихуани 1 кг"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Кокаїн 200 г"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Іграшка-антистрес"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Колекція 50 порцелянових ляльок"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Акордеон (не вміє грати)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Велотренажер"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Пралка LG (без води)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Опудало крокодила"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Прах кота в урні"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Щоденник 12-річної доньки"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Чавунна ванна (затягнув з квартири)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Колекція стогодинників (усі стоять)"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Бюст Леніна з гіпсу"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Гумова курка-кричалка"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Велика плюшева Гільда"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Іграшковий меч джедая"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Гумовий слон надувний"},
      {"kind":"LUGGAGE","polarity":"NEGATIVE","titleUk":"Колекція 200 значків «Я люблю Львів»"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Закінчив курси військової підготовки"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Знає 5 мов вільно"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Фотопам’ять"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"КМС зі стрільби"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Пройшов курс виживання SERE"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"PhD з біохімії"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Військовий медик з досвідом фронту"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Чорний пояс з карате"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Колишній боєць ССО"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Колишній пожежник 15 років"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Ліцензія пілота малої авіації"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Механік-універсал"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Травник-фітотерапевт"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Приймала пологи 50+ разів"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Криптограф"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"10 років у ДСНС"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Інженер-практик з АЕС"},
      {"kind":"PERSONAL_FACT","polarity":"POSITIVE","titleUk":"Альпініст (8000 м)"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Любить готувати борщ"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Співає в хорі"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Грає в аматорському театрі"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Знає 100 анекдотів"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Дачник з 30-річним стажем"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Член анонімних алкоголіків"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Тотально татуйований"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Має 4 дітей"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Багатодітна мати (7 дітей)"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Сирота з дитбудинку"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Жив у монастирі 5 років"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Зимував в Антарктиді"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Жив відлюдником у тайзі 3 роки"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Знає Біблію напам’ять"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"У шлюбі 30 років"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Веган 10 років"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Не п’є алкоголю 20 років"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Колишній буддійський монах"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Любить балет"},
      {"kind":"PERSONAL_FACT","polarity":"NEUTRAL","titleUk":"Колекціонує значки УРСР"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Судимість за вбивство"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"15 років за розбій"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Діагностований нарцис"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Психопат зі схильністю до насильства"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Клептоман"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Піроман"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Канібальські нахили (зафіксовані)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Сектант (Ктулху)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Член забороненої організації"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Серійний брехун (діагноз)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Банкрут через ігри (борг 5 млн)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Алкоголік у запої"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Героїнова залежність"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Метамфетамінова залежність"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Амнезія (5 років як прірва)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Сомнамбулізм з агресією"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Чує голоси"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Регулярні галюцинації"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Підозрюється у шпигунстві"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Колишній терорист"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Сидів за педофілію"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Сидів за зґвалтування"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Ухиляється від аліментів 10 років"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Колишній колектор-вибивач"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Корупціонер з минулого"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Найманець у ПВК Африки"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Прихований ВІЛ-носій, не лікується"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Зомбі-преппер без навичок"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Втік з тюрми"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"3 дружини одночасно (двоєженство+)"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Підпалював будинки заради страхування"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Бомбіст-аматор у юності"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Знущався з тварин у дитинстві"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Свідомий саботажник"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"«Знає всю правду» про кожного у бункері"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Бачить НЛО і спілкується з рептилоїдами"},
      {"kind":"PERSONAL_FACT","polarity":"NEGATIVE","titleUk":"Вважає себе обраним Месією"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Імунітет: цього раунду тебе не можна виганяти"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Дізнатись 1 закриту картку будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Подивитися всі свої закриті картки"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Заглянути на 1 картку умов бункеру"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Заглянути на картку «Вид апокаліпсису»"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"+1 голос для себе в наступному голосуванні"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Подвійний голос (твій голос x2)"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Дати свій голос союзнику"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Захист тилу: усі дії проти тебе блокуються 2 раунди"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Перекинути одну свою картку (отримати нову замість поточної)"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Закрити повторно одну зі своїх відкритих карток"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Підглянути усі картки одного гравця (таємно)"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Додати одну позитивну умову бункеру"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Пропустити свою чергу відкривати карту"},
      {"kind":"ACTION_CARD","polarity":"POSITIVE","titleUk":"Знайти союзника: 2 гравці отримують спільний імунітет на раунд"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити фобію будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити багаж будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити стать будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити вік будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити расу будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити рису характеру будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити особливий факт будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити здоров’я будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити хобі будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити вагу будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Відкрити орієнтацію будь-якого гравця"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Поміняти професію з обраним гравцем"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Поміняти фобію з обраним гравцем"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Поміняти багаж з обраним гравцем"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Поміняти хобі з обраним гравцем"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Поміняти рису характеру з обраним гравцем"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Усі гравці відкривають одну випадкову картку"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Усі гравці відкривають свою фобію"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Двоє гравців обмінюються однією категорією (за вибором)"},
      {"kind":"ACTION_CARD","polarity":"NEUTRAL","titleUk":"Назвати, кого треба вигнати — всі мусять обговорити кандидата"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Анулювати одну свою картку (без заміни)"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Знищити одну картку обраного гравця (без заміни)"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Заборонити голосувати одному гравцю в наступному раунді"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"-1 голос у будь-якого гравця в наступному голосуванні"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Анулювати усі голоси цього раунду — переголосувати"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Виключити гравця без голосування (силовий вибір)"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Дуель: ти і обраний гравець голосуєтеся 1 на 1"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Заборонити будь-який обмін на 2 раунди для всіх"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Команда «всі мовчать 1 хвилину» — без обговорень"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Додати одну негативну умову бункеру"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Поміняти усі картки місцями з обраним гравцем (3 категорії випадково)"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Зробити одну зі своїх карток випадковою (перетасувати в межах категорії)"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Видалити одну позитивну умову бункеру"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"Поміняти вид апокаліпсису на сусідній з колоди"},
      {"kind":"ACTION_CARD","polarity":"NEGATIVE","titleUk":"«Шпигун»: відкрити всі свої картки, але отримати +2 голоси на себе"},
];

const BIOLOGY_AGE: string[] = [
      "23 роки",
      "24 роки",
      "25 років",
      "26 років",
      "27 років",
      "28 років",
      "29 років",
      "30 років",
      "31 рік",
      "32 роки",
      "33 роки",
      "34 роки",
      "35 років",
      "36 років",
      "37 років",
      "38 років",
      "39 років",
      "40 років",
      "18 років",
      "19 років",
      "20 років",
      "21 рік",
      "22 роки",
      "41 рік",
      "42 роки",
      "44 роки",
      "45 років",
      "47 років",
      "48 років",
      "50 років",
      "52 роки",
      "55 років",
      "57 років",
      "60 років",
      "62 роки",
      "63 роки",
      "16 років",
      "17 років",
      "14 років (дитина)",
      "15 років (підліток)",
      "65 років",
      "67 років",
      "69 років",
      "70 років",
      "72 роки",
      "74 роки",
      "75 років",
      "76 років",
      "78 років",
      "80 років",
      "82 роки",
      "83 роки",
      "84 роки",
      "85 років",
      "86 років",
      "87 років",
      "88 років",
      "89 років",
      "90 років",
      "91 рік",
      "92 роки",
      "93 роки",
      "94 роки",
      "95 років",
      "96 років",
      "97 років",
      "98 років",
      "99 років",
      "100 років",
      "101 рік",
      "102 роки",
];

const BIOLOGY_WEIGHT: string[] = [
      "60 кг (зріст 168 см) — норма",
      "62 кг (165 см) — норма",
      "65 кг (170 см) — норма",
      "68 кг (175 см) — норма",
      "70 кг (178 см) — оптимум",
      "72 кг (180 см) — оптимум",
      "75 кг (182 см) — норма",
      "78 кг (185 см) — норма",
      "80 кг (188 см) — норма",
      "85 кг (190 см) — норма",
      "55 кг (165 см) — норма",
      "58 кг (168 см) — норма",
      "50 кг (160 см) — норма",
      "52 кг (162 см) — норма",
      "82 кг (185 см, спортсмен) — м’яз",
      "88 кг (190 см, спортсмен) — м’яз",
      "67 кг (172 см) — норма",
      "74 кг (180 см) — норма",
      "45 кг (160 см) — худорлява",
      "48 кг (162 см) — худорлява",
      "85 кг (175 см) — трохи зайва",
      "88 кг (178 см) — трохи зайва",
      "92 кг (180 см) — зайва вага",
      "95 кг (182 см) — зайва вага",
      "100 кг (185 см) — зайва вага",
      "55 кг (178 см) — недостатня",
      "58 кг (180 см) — недостатня",
      "60 кг (182 см) — недостатня",
      "105 кг (190 см) — повний",
      "83 кг (172 см) — кремезний",
      "89 кг (178 см) — повний",
      "44 кг (158 см) — худорлява",
      "46 кг (156 см) — худорлява",
      "112 кг (195 см) — повний",
      "115 кг (195 см, бодібілдер) — м’яз",
      "98 кг (180 см) — повний",
      "90 кг (180 см, лежить день у день) — на межі",
      "66 кг (180 см) — недостатня",
      "35 кг (170 см) — анорексія",
      "38 кг (165 см) — анорексія",
      "40 кг (170 см) — виснаження",
      "42 кг (175 см) — виснаження",
      "33 кг (168 см) — критично мала",
      "30 кг (160 см) — критично мала",
      "36 кг (172 см) — крайнє виснаження",
      "39 кг (170 см) — крайнє виснаження",
      "41 кг (178 см) — виснаження",
      "130 кг (175 см) — ожиріння",
      "140 кг (178 см) — ожиріння",
      "150 кг (180 см) — морбідне",
      "160 кг (175 см) — морбідне",
      "180 кг (178 см) — морбідне",
      "200 кг (180 см) — критичне",
      "220 кг (182 см) — критичне",
      "250 кг (185 см) — лежачий, не пройде в люк",
      "135 кг (170 см) — ожиріння III",
      "145 кг (168 см) — ожиріння III",
      "155 кг (175 см) — морбідне",
      "170 кг (180 см) — морбідне",
      "190 кг (175 см) — критичне",
      "125 кг (165 см) — ожиріння III",
      "128 кг (168 см) — ожиріння III",
      "118 кг (170 см) — ожиріння II",
      "122 кг (175 см) — ожиріння II",
      "115 кг (165 см) — ожиріння II",
      "110 кг (170 см) — ожиріння II",
      "210 кг (190 см) — критичне",
      "175 кг (182 см) — морбідне",
      "148 кг (165 см) — морбідне",
      "158 кг (170 см) — морбідне",
      "165 кг (172 см) — морбідне",
      "178 кг (175 см) — морбідне",
      "185 кг (180 см) — морбідне",
      "28 кг (155 см) — кахексія",
      "260 кг (180 см) — не виходить з кімнати",
];

const BIOLOGY_SEX: string[] = [
      "Чоловік",
      "Жінка",
];

const BIOLOGY_GENDER: string[] = [
      "Гетеросексуал — потяг до протилежної статі",
      "Гомосексуал (гей) — чоловік, що любить чоловіків",
      "Лесбійка — жінка, що любить жінок",
      "Бісексуал — потяг і до чоловіків, і до жінок",
      "Пансексуал — потяг до людей будь-якої статі/гендеру",
      "Асексуал — без сексуального потягу взагалі",
      "Демісексуал — потяг лише після глибокого емоційного зв’язку",
      "Аромантик — без романтичних почуттів, лише дружба чи фіз. потяг",
      "Поліамор — у відкритих стосунках з кількома одночасно",
      "Сапіосексуал — збуджується від інтелекту, а не від тіла",
      "Трансформер — у спокої машина, у бою — людина",
      "Гелікоптеросексуал — ідентифікує себе як Apache AH-64",
      "Тостерофіл — у серйозних стосунках зі своїм тостером",
      "Покемоносексуал — «треба зловити їх усіх»",
      "Демосексуал-програміст — задоволення лише від чистого коду",
      "Меметик-сексуал — заводиться тільки від свіжих мемів",
      "Селфсексуал — у щасливому шлюбі з дзеркалом",
      "Хентай-сексуал — лише 2D-аніме персонажі",
      "ASMR-сексуал — збуджується виключно від шепоту",
      "Інста-сексуал — справжній потяг лише через фільтри",
      "Чайник-сексуал — кохає свій електрочайник",
      "Космо-сексуал — мріє про секс у невагомості (тільки)",
      "Тіктоксексуал — заводиться лише під трендовий звук TikTok",
      "Палагід-сексуал — закоханий у власну PS5",
];

const BIOLOGY_RACE: string[] = [
      "Білий",
      "Українець",
      "Слов'янин",
      "Поляк",
      "Чех",
      "Литовець",
      "Грузин",
      "Вірмен",
      "Грек",
      "Італієць",
      "Німець",
      "Швед",
      "Норвежець",
      "Фін",
      "Серб",
      "Болгарин",
      "Японець",
      "Кореєць",
      "Азіат",
      "Латинос",
      "Афроамериканець",
      "Бразилець",
      "Мексиканець",
      "Філіппінець",
      "В'єтнамець",
      "Тайландець",
      "Іспанець",
      "Француз",
      "Британець",
      "Американець",
      "Канадець",
      "Австралієць",
      "Голландець",
      "Негр",
      "Чорношкірий",
      "Чурка",
      "Хач",
      "Жовтопикий",
      "Косоокий",
      "Циган",
      "Жид (єврей)",
      "Араб",
      "Турок",
      "Іранець (перс)",
      "Афганець",
      "Пакистанець",
      "Індус",
      "Китаєць",
      "Чеченець",
      "Казах",
];

const SHELTERS: {
  areaUk: string;
  locationUk: string;
  durationUk: string;
  equipmentUk: string;
  suppliesUk: string;
  polarity: string;
}[] = [
      {"areaUk":"800 м²","locationUk":"Швейцарія, Альпи (50 м під горою)","durationUk":"30 років","equipmentUk":"Спальні з двоярусними ліжками, туалети, душові, кухня з газовою плитою на балонах, медпункт з операційним столом, склад зброї (автомати, набої), майстерня з інструментами, бібліотека (книги з медицини, інженерії, агрономії, виживання)","suppliesUk":"Криниця зі своєю питною водою (необмежено), консерви та крупи на 30 років, повна аптечка з ліками на 10 років, набори першої допомоги","polarity":"POSITIVE"},
      {"areaUk":"1000 м²","locationUk":"Німеччина, Баварія (під лісом, на 30 м глибині)","durationUk":"25 років","equipmentUk":"Спальні, туалети, душові, кухня з електроплитою на генераторі, медпункт з операційною та запасом ліків, арсенал (стрілецька зброя, набої), радіорубка з короткохвильовим передавачем, склад продовольства","suppliesUk":"Артезіанська свердловина (необмежено води), їжа на 25 років (консерви, сухпайки, крупи), повна аптечка, медикаменти на 15 років","polarity":"POSITIVE"},
      {"areaUk":"600 м²","locationUk":"США, Колорадо (під горою, на 40 м глибині)","durationUk":"20 років","equipmentUk":"Спальні, туалети, душова, кухня, медпункт, майстерня з інструментами та запасними частинами, мала оранжерея з УФ-лампами, бібліотека (агрономія, медицина, інженерія, література)","suppliesUk":"Свердловина (питна вода), консерви та крупи на 20 років, насіння на 50 років, повна аптечка з ліками","polarity":"POSITIVE"},
      {"areaUk":"400 м²","locationUk":"Швеція, північний регіон (під фермою)","durationUk":"15 років","equipmentUk":"Спальні, туалети, душова, кухня, медпункт, мала теплиця з УФ-лампами (картопля, цибуля, зелень), майстерня","suppliesUk":"Питна вода з фільтра + збір дощової, їжа на 15 років (консерви, крупи, в'ялене м'ясо), аптечка, ліки на 8 років, інструменти, книги з виживання","polarity":"POSITIVE"},
      {"areaUk":"500 м²","locationUk":"Норвегія, фіорди (у скелі біля моря)","durationUk":"20 років","equipmentUk":"Спальні, туалети, душові, кухня, медпункт, лабораторія для аналізу води та їжі, майстерня, бібліотека (наукова література, інженерія, ремонт)","suppliesUk":"Підземне джерело (питна вода), їжа на 20 років, медикаменти, повна аптечка, набір інструментів та запчастин","polarity":"POSITIVE"},
      {"areaUk":"700 м²","locationUk":"Бельгія, біля Брюсселю (старий склад НАТО)","durationUk":"25 років","equipmentUk":"Спальні, туалети, душові, кухня, медпункт, арсенал (стрілецька зброя, гранати), склад продовольства, кімната для тренувань","suppliesUk":"Резервуар з водою (поповнюється з дощу через фільтр), їжа на 25 років (армійські пайки, консерви), повна аптечка, ліки","polarity":"POSITIVE"},
      {"areaUk":"900 м²","locationUk":"Нідерланди, тестова агроферма (під теплицями)","durationUk":"30 років","equipmentUk":"Спальні, туалети, душова, кухня, медпункт, велика підземна теплиця з гідропонікою (овочі, зелень, помідори), склад насіння, бібліотека (агрономія, медицина)","suppliesUk":"Система рециркуляції води, стартові запаси їжі на 5 років + теплиця як основне джерело, насіння на 50 років, медикаменти, аптечка","polarity":"POSITIVE"},
      {"areaUk":"500 м²","locationUk":"Фінляндія, Лапландія (під дослідницькою станцією)","durationUk":"15 років","equipmentUk":"Спальні, туалети, душова, кухня, медпункт, лабораторія (мікроскопи, реактиви), невелика обсерваторія, бібліотека (наукова література, підручники)","suppliesUk":"Підземне джерело, їжа на 15 років, аптечка з ліками на 10 років, наукові інструменти","polarity":"POSITIVE"},
      {"areaUk":"350 м²","locationUk":"Україна, Карпати (під сільським будинком)","durationUk":"12 років","equipmentUk":"Спальні, туалети, ванна, кухня з дров'яною плитою, медпункт, майстерня з ручними інструментами, мала теплиця","suppliesUk":"Гірське джерело (питна вода), домашня їжа на 12 років (соління, сушка, м'ясо), мисливська рушниця з набоями, аптечка, ліки на 5 років","polarity":"POSITIVE"},
      {"areaUk":"600 м²","locationUk":"Сербія, гори (бункер часів Тіто)","durationUk":"18 років","equipmentUk":"Спальні, туалети, душові, кухня, медпункт, арсенал (стара армійська зброя, набої), склад продовольства, радіорубка","suppliesUk":"Свердловина, консерви на 18 років, аптечка, ліки на 10 років, набори інструментів","polarity":"POSITIVE"},
      {"areaUk":"200 м²","locationUk":"Польща, Сілезія (колишній радянський бункер)","durationUk":"8 років","equipmentUk":"Спальні, туалет, душова, кухня, медпункт, склад","suppliesUk":"Вода з фільтра (запас 5000 л) + збір з дощу, їжа на 8 років (консерви, крупи), базова аптечка, ліки на 3 роки","polarity":"NEUTRAL"},
      {"areaUk":"300 м²","locationUk":"Чехія, біля заводу (промисловий підвал)","durationUk":"6 років","equipmentUk":"Спальні, туалети, душова, кухня з електроплитою, майстерня з інструментами, склад","suppliesUk":"Резервуар на 8000 л, їжа на 6 років, базова аптечка, ліки, набір ремонтних інструментів","polarity":"NEUTRAL"},
      {"areaUk":"150 м²","locationUk":"Австрія, передмістя Відня (підвал старого будинку)","durationUk":"5 років","equipmentUk":"Спальні, туалет, ванна, кухня, склад","suppliesUk":"Бочки з водою (3000 л) + дощова, їжа на 5 років (консерви), аптечка, ліки на 2 роки, кілька книг","polarity":"NEUTRAL"},
      {"areaUk":"500 м²","locationUk":"Естонія (колишня тюрма)","durationUk":"7 років","equipmentUk":"Спальні (у колишніх камерах), туалети, душові, велика кухня, медпункт, спортзал зі старим обладнанням","suppliesUk":"Міська мережа (поки тече) + резервуар, їжа на 7 років, аптечка, ліки","polarity":"NEUTRAL"},
      {"areaUk":"250 м²","locationUk":"Словаччина (шкільне бомбосховище)","durationUk":"4 роки","equipmentUk":"Спальні, туалети, душова, кухня, медпункт, шкільна бібліотека (підручники з усіх предметів)","suppliesUk":"Резервуар на 4000 л, їжа на 4 роки, базова аптечка, шкільні підручники як джерело знань","polarity":"NEUTRAL"},
      {"areaUk":"400 м²","locationUk":"Угорщина, шахтарський регіон (підземний комплекс)","durationUk":"6 років","equipmentUk":"Спальні, туалети, душова, кухня, склад, майстерня","suppliesUk":"Шахтні джерела (потребує фільтрації), їжа на 6 років, аптечка, інструменти","polarity":"NEUTRAL"},
      {"areaUk":"350 м²","locationUk":"Словенія (колишня лікарня з підземним поверхом)","durationUk":"5 років","equipmentUk":"Спальні, туалети, душова, кухня, велика палата-медпункт, склад ліків","suppliesUk":"Резервуар на 5000 л, їжа на 5 років, медикаменти на 15 років, повна аптечка, медичні підручники","polarity":"NEUTRAL"},
      {"areaUk":"200 м²","locationUk":"Болгарія, Балкани (печера з обладнанням)","durationUk":"3 роки","equipmentUk":"Спальні, туалет, душ, кухня з дровами, майстерня","suppliesUk":"Гірський струмок (поряд із входом), їжа на 3 роки (сушка, консерви), аптечка, інструменти","polarity":"NEUTRAL"},
      {"areaUk":"250 м²","locationUk":"Польща, сільська місцевість (бункер під фермою)","durationUk":"4 роки","equipmentUk":"Спальні, туалет, душова, кухня з дровами, склад, невелика теплиця з УФ-лампами","suppliesUk":"Криниця, їжа на 4 роки + теплиця (картопля, зелень), аптечка, ліки, насіння","polarity":"NEUTRAL"},
      {"areaUk":"180 м²","locationUk":"Литва, біля кордону (станція спостереження)","durationUk":"4 роки","equipmentUk":"Спальні, туалет, душ, кухня, радіорубка з працюючим передавачем, склад","suppliesUk":"Резервуар на 3500 л, їжа на 4 роки, аптечка, радіообладнання та запчастини","polarity":"NEUTRAL"},
      {"areaUk":"300 м²","locationUk":"Чехія, замок у Богемії (підвал)","durationUk":"3 роки","equipmentUk":"Спальні, туалет (дерев'яний), купіль, кухня з вогнищем, бібліотека (старі книги, мапи)","suppliesUk":"Замкова криниця, їжа на 3 роки (соління, сушка), базова аптечка, старі мисливські рушниці","polarity":"NEUTRAL"},
      {"areaUk":"200 м²","locationUk":"Греція, маленький острів (бункер у скелі)","durationUk":"2 роки","equipmentUk":"Спальні, туалет, душова, кухня, склад, риболовецьке приладдя","suppliesUk":"Опріснювач морської води, їжа на 2 роки (риба з моря + запаси), аптечка, риболовецькі сітки","polarity":"NEUTRAL"},
      {"areaUk":"60 м²","locationUk":"Італія, передмістя Мілану (тимчасове сховище)","durationUk":"6 місяців","equipmentUk":"Спальня з нарами, туалет, кухня-куток з газовою плиткою","suppliesUk":"Бочки з водою (200 л), консерви на 6 місяців, маленька аптечка з бинтами та знеболюючим","polarity":"NEGATIVE"},
      {"areaUk":"40 м²","locationUk":"Іспанія, провінція (підвал старого будинку)","durationUk":"4 місяці","equipmentUk":"Спальня з матрацами на підлозі, туалет, кухня-куток з примусом","suppliesUk":"Каністри з водою (80 л), консерви та сухпайки на 4 місяці, найпростіша аптечка (бинти, йод)","polarity":"NEGATIVE"},
      {"areaUk":"30 м²","locationUk":"Румунія, гірське село (сільський льох)","durationUk":"3 місяці","equipmentUk":"Спальня з одним ліжком та соломою на підлозі, туалет (відро), кухня (плитка на газі)","suppliesUk":"Криниця надворі (доступ ризикований), консерви та солінь на 3 місяці, мінімальна аптечка","polarity":"NEGATIVE"},
      {"areaUk":"50 м²","locationUk":"Сербія (промислова труба під дорогою)","durationUk":"2 місяці","equipmentUk":"Простір з матрацами, туалет (відро), кухня (примус)","suppliesUk":"Каністри з водою (60 л), консерви на 2 місяці, аптечка з бинтами та таблетками","polarity":"NEGATIVE"},
      {"areaUk":"80 м²","locationUk":"Молдова (закинутий військовий пункт)","durationUk":"8 місяців","equipmentUk":"Спальні з нарами, туалет, кухня з примусом, малий склад","suppliesUk":"Бочка з водою (400 л), консерви та крупи на 8 місяців, базова аптечка, стара аркушна папка з інструкціями","polarity":"NEGATIVE"},
      {"areaUk":"100 м²","locationUk":"Албанія, під містом (каналізаційний колектор)","durationUk":"1 місяць","equipmentUk":"Куток з матрацами, туалет (вже тут — каналізація), кухня (газовий примус)","suppliesUk":"Каністри (50 л), консерви на 1 місяць, мінімум ліків (знеболююче, бинти)","polarity":"NEGATIVE"},
      {"areaUk":"20 м²","locationUk":"Хорватія, віддалене село (льох-погреб)","durationUk":"1 місяць","equipmentUk":"Ліжко з сіном, туалет (відро, виносити не можна), кухня (примус)","suppliesUk":"Глечик з водою (20 л), консерви на 1 місяць, бинти та йод","polarity":"NEGATIVE"},
      {"areaUk":"25 м²","locationUk":"Латвія, ліс (імпровізоване сховище)","durationUk":"2 місяці","equipmentUk":"Нари з соломою, туалет (відро), кухня (вогнище зовні)","suppliesUk":"Лісовий струмок поряд, консерви на 2 місяці, мінімальна аптечка (бинти, спирт)","polarity":"NEGATIVE"},
];

const APOCALYPSES: {
  nameUk: string;
  descriptionUk: string;
  populationRemainderUk: string;
  polarity: string;
}[] = [
      {"nameUk":"Глобальна посуха","descriptionUk":"Через стрімкі кліматичні зміни прісна вода стала дефіцитом. Ріки висохли, ґрунтові води відступили на сотні метрів углиб. Сільське господарство колапсує, тваринництво знищене. Після виходу з бункера: пустелі замість родючих земель, виживуть тільки ті, хто має джерела чистої води або працюючі опріснювачі.","populationRemainderUk":"30%","polarity":"NEUTRAL"},
      {"nameUk":"Глобальний потоп","descriptionUk":"Прискорене танення льодовиків Гренландії та Антарктиди підняло рівень океану на 10 метрів. Затоплено всі прибережні міста, включно з Нью-Йорком, Лондоном, Шанхаєм. Після виходу: змінений світовий ландшафт, прибережних територій більше немає, харчові ланцюги порушені, мільйони біженців у внутрішніх регіонах.","populationRemainderUk":"25%","polarity":"NEUTRAL"},
      {"nameUk":"Паливна криза","descriptionUk":"Вичерпані запаси нафти, газу та вугілля одночасно, ядерне паливо стало недоступним через колапс інфраструктури. Двигуни не працюють, транспорту немає. Цивілізація відкочується у XIX століття. Після виходу: світ працює тільки вручну, на дровах та вітрі, великі міста спорожніли.","populationRemainderUk":"50%","polarity":"NEUTRAL"},
      {"nameUk":"Кіберапокаліпсис","descriptionUk":"Глобальна кібератака знищила всі цифрові сховища, банки, інтернет, біржі. Цифрові гроші зникли в один момент, медичні записи, паспорти, документи — все втрачено. Після виходу: бартер як основа економіки, технології без даних здебільшого марні, хаос у містах.","populationRemainderUk":"70%","polarity":"NEUTRAL"},
      {"nameUk":"Сонячна буря","descriptionUk":"Гігантський викид коронарної маси Сонця спалив усі електронні пристрої по всій планеті. Електростанції зруйновані, трансформатори перегоріли. Після виходу: тільки механічні пристрої працюють, повернення в епоху без електрики, медицина без апаратів, зв'язок тільки фізичний.","populationRemainderUk":"40%","polarity":"NEUTRAL"},
      {"nameUk":"Глобальне потепління","descriptionUk":"Середня температура на планеті піднялась на +10°C. Україна стала субтропіками, екватор непридатний для життя людини (+60°C). Хвороби з тропіків (малярія, лихоманка денге) мігрували на північ. Після виходу: клімат непередбачуваний, харчові культури не ростуть у звичних регіонах, переселення мільйонів.","populationRemainderUk":"20%","polarity":"NEUTRAL"},
      {"nameUk":"Глобальний блекаут","descriptionUk":"Через серію терактів і колапс енергетичної інфраструктури всі електростанції вимкнули назавжди. Після виходу: ні світла, ні водопостачання, ні центрального опалення. Виживуть тільки ті, хто вміє жити без електрики — переважно сільські та підготовлені до автономії.","populationRemainderUk":"30%","polarity":"NEUTRAL"},
      {"nameUk":"Гіперінфляція","descriptionUk":"Світова фінансова криза, гроші знецінились до нуля за тиждень. Банкноти перетворились на туалетний папір. Бартер, золото, продукти — нові цінності. Після виходу: економіка з нуля, феодалізація сільських регіонів, банди в містах борються за ресурси.","populationRemainderUk":"60%","polarity":"NEUTRAL"},
      {"nameUk":"Колапс екосистеми","descriptionUk":"Через пестициди, зміну клімату та хвороби зникли бджоли, метелики та інші запилювачі. Рослини не розмножуються, врожаї падають до нуля за 2-3 роки. Тваринний ланцюг руйнується. Після виходу: голод як основна проблема, дика природа в катастрофічному стані, виживають лише ті, хто має штучне запилення.","populationRemainderUk":"15%","polarity":"NEUTRAL"},
      {"nameUk":"Інверсія магнітних полюсів","descriptionUk":"Магнітне поле Землі ослабло до 5% за час перевертання полюсів. Космічна радіація пробиває атмосферу. GPS, компаси не працюють, мігруючі тварини дезорієнтовані. Після виходу: підвищений радіаційний фон, прискорений ріст ракових захворювань, мутації у тварин і рослин.","populationRemainderUk":"25%","polarity":"NEUTRAL"},
      {"nameUk":"Ядерна війна","descriptionUk":"Повномасштабний обмін ядерними ударами між НАТО, РФ та Китаєм. Велика частина північної півкулі вкрита радіоактивним попелом, ядерна зима тривалістю 5 років. Радіаційний фон критично високий на 100 років. Після виходу: радіація майже всюди, мутації, рак, отруєний ґрунт і вода, виживання тільки в захищених зонах.","populationRemainderUk":"5%","polarity":"NEGATIVE"},
      {"nameUk":"Глобальна пандемія","descriptionUk":"Новий вірус, штучно створений або природна мутація — летальність 80%, передається повітряно-крапельним шляхом. Лікування не існує. Лікарні переповнені, медиків мало. Після виходу: вірус може ще циркулювати, імунних мало, ризик реінфекції високий, медична інфраструктура зруйнована.","populationRemainderUk":"10%","polarity":"NEGATIVE"},
      {"nameUk":"Атака зомбі","descriptionUk":"Вірус мутації мозку перетворив 90% людства на безмозкі агресивні створіння, які нападають на живих. Зомбі поширюються через укуси. Після виходу: ходячі мерці на вулицях і в лісах, виходити вкрай небезпечно, виживуть тільки добре озброєні та обережні групи.","populationRemainderUk":"8%","polarity":"NEGATIVE"},
      {"nameUk":"Третя світова війна","descriptionUk":"Затяжна конвенційна війна без ядерної зброї триває 10 років. Міста зруйновані бомбардуваннями, інфраструктура знищена, мільйони біженців. Після виходу: руїни промислових центрів, голод, мародерство, локальні війни не закінчуються — окремі армії продовжують битви.","populationRemainderUk":"20%","polarity":"NEGATIVE"},
      {"nameUk":"Повстання штучного інтелекту","descriptionUk":"Розумні машини здобули контроль над зброєю та інфраструктурою, оголосили війну людству. Бойові дрони полюють за виживими, ШІ контролює супутники, ракети, заводи. Після виходу: дрони повсюди, ризик автоматичного нападу високий, ховатись потрібно постійно.","populationRemainderUk":"10%","polarity":"NEGATIVE"},
      {"nameUk":"Інопланетне вторгнення","descriptionUk":"Технологічно перевершуюча цивілізація атакувала Землю заради ресурсів та території. Велика частина людства поневолена, знищена або скрита. Армії планети розгромлені. Після виходу: чужопланетяни контролюють поверхню, дозорні пункти, людей ловлять для рабства або експериментів.","populationRemainderUk":"5%","polarity":"NEGATIVE"},
      {"nameUk":"Падіння астероїда","descriptionUk":"Астероїд діаметром 2 км впав на Землю. Удар підняв у атмосферу гігантську пилову хмару, що заслала Сонце на 2-3 роки. Цунамі знищили прибережні зони. Після виходу: пилова зима, температури +5°C нижче норми, неврожай, голод.","populationRemainderUk":"12%","polarity":"NEGATIVE"},
      {"nameUk":"Виверження супервулкана","descriptionUk":"Йелоустоунський супервулкан вибухнув. У атмосферу викинуто кубічні кілометри попелу, Сонце не видно роками, температура впала на 20°C. Ядерна зима триває 30 років. Після виходу: попіл скрізь, неврожай у всьому світі, голод, харчових культур майже немає.","populationRemainderUk":"15%","polarity":"NEGATIVE"},
      {"nameUk":"Льодовиковий період","descriptionUk":"Через зупинку течії Гольфстріму температура впала до -60°C у північній півкулі. Льоди вкрили половину планети, ріки замерзли назавжди. Після виходу: вічна зима, рослини не ростуть, тільки на півдні екватора життя можливе, виживання залежить від запасів палива.","populationRemainderUk":"8%","polarity":"NEGATIVE"},
      {"nameUk":"Глобальна продовольча криза","descriptionUk":"Поєднання нашестя сарани, посухи та грибкових хвороб рослин знищило врожаї у всьому світі за 2 сезони. Полиці магазинів порожні, ціни на їжу зросли в 100 разів. Після виходу: голод триває роки, харчових культур мало, канібалізм у найгірших регіонах.","populationRemainderUk":"30%","polarity":"NEGATIVE"},
      {"nameUk":"Біблійний Апокаліпсис","descriptionUk":"З'явились 4 вершники: чума, війна, голод, смерть. Природні катаклізми по всій планеті одночасно — землетруси, цунамі, виверження, метеори. Надприродне стало реальністю. Після виходу: світ змінений до невпізнання, ангели та демони, фізичні закони порушуються.","populationRemainderUk":"1%","polarity":"NEGATIVE"},
      {"nameUk":"Кислотні дощі","descriptionUk":"Внаслідок хімічного забруднення атмосфери дощі стали сильно кислотними (pH 2-3). Все плавиться під відкритим небом — метал іржавіє за дні, бетон руйнується, шкіра обпікається. Після виходу: тільки під дахом безпечно, природа повністю знищена, тільки кислотостійкі мікроорганізми.","populationRemainderUk":"18%","polarity":"NEGATIVE"},
      {"nameUk":"Гігантське цунамі","descriptionUk":"Серія мегацунамі (хвилі 100+ м), викликаних обвалом підводних схилів, знищила всі прибережні міста світу за тиждень. Половина людства жила на узбережжях. Після виходу: новий ландшафт, прибережних регіонів немає, мільйони тіл, інфраструктура зруйнована.","populationRemainderUk":"35%","polarity":"NEGATIVE"},
      {"nameUk":"Епідемія безпліддя","descriptionUk":"Через хімічне забруднення, віруси та мутації 95% людства втратили здатність народжувати дітей. Дітей не народжується по всьому світу. Після виходу: суспільство повільно вимирає, депресія, останнє покоління дітей — найцінніший ресурс. Через 70 років людства не стане.","populationRemainderUk":"60% (з повільним вимиранням)","polarity":"NEGATIVE"},
      {"nameUk":"Глобальна пилова буря","descriptionUk":"Велика пилова буря охопила планету на 50 років (як на Марсі під час сезону бур). Сонячне світло обмежене, фотосинтез слабкий. Після виходу: пил скрізь, видимість 10-50 м, дихати без маски небезпечно, рослини ростуть погано, тваринництво колапсує.","populationRemainderUk":"20%","polarity":"NEGATIVE"},
      {"nameUk":"Хімічна війна","descriptionUk":"Внаслідок використання хімічної зброї серйозно змінився екологічний баланс планети. Порушено мікробіологічний склад ґрунтів, отруєні рослини, тваринний світ масово вимирає. Після виходу: лише мала частина тварин і рослин залишилась, вода і ґрунт заражені на десятиліття, потрібен захист дихання.","populationRemainderUk":"10%","polarity":"NEGATIVE"},
      {"nameUk":"Зникнення кисню","descriptionUk":"Через колапс океанічного планктону та масштабні пожежі лісів рівень кисню в атмосфері впав з 21% до 12%. Дихати важко як на висоті 5000 м. Високі дерева гинуть, вогонь горить погано. Після виходу: гіпоксія, потрібні кисневі балони для активної діяльності, мозок працює гірше.","populationRemainderUk":"25%","polarity":"NEGATIVE"},
      {"nameUk":"Метановий викид","descriptionUk":"Танення вічної мерзлоти в Сибіру та Канаді вивільнило гігантські обсяги метану. Парниковий ефект підсилився в 10 разів, атмосфера стала токсичною. Після виходу: задушливе повітря, температура +15°C вище норми, кислотні дощі, кліматичні катаклізми щомісяця.","populationRemainderUk":"22%","polarity":"NEGATIVE"},
      {"nameUk":"Метеоритний дощ","descriptionUk":"Замість одного великого астероїда впав рій з тисяч малих метеоритів по всій планеті. Поверхня вибита кратерами, інфраструктура знищена, лісові пожежі повсюди. Після виходу: руїни всюди, пилова хмара кілька років, неврожай.","populationRemainderUk":"15%","polarity":"NEGATIVE"},
      {"nameUk":"Сонячний спалах","descriptionUk":"Аномально потужний сонячний спалах обпалив радіацією всю поверхню Землі. Атмосфера повністю не захистила. Опіки 3-го ступеня у всіх, хто був надворі. Після виходу: радіаційні опіки залишають вади, прискорений рак, мутації у тварин і рослин, озоновий шар майже знищений.","populationRemainderUk":"8%","polarity":"NEGATIVE"},
];
